### ISSUE TITLE
Googlebot, yahoo and bingbot are in not allowed users agents

### ISSUE THREAD

**Issue by ka8725** [prerender/prerender_rails#19]
Does it mean that the bots won't give response? This comment [looks](https://github.com/prerender/prerender_rails/blob/master/lib/prerender_rails.rb#L7-L9) confused. It's not clear why they are removed from the list. Could you expand the comment, please?
If we don't have the bots in the allowed lists does it mean that Google will not index the site?

**Comment by thoop** [comment]
No. Google, Yahoo, and Bing will definitely get prerendered pages. We just don't check them by user agent. They will send the `_escaped_fragment_` query parameter instead, which we also check for in the middleware. Google, Yahoo, and Bing are supported and will index your site by default using the Prerender middleware. I'll update that comment to make it more explicit.
