### ISSUE TITLE
Prerender my homepage is taking a life

### ISSUE THREAD

**Issue by blanchma** [prerender/prerender_rails#21]
My app is build with angular and when I try to crawl it with Facebook URL Debugger I get a timeout. I use a local server to test the middleware and it never ends. I also try to cache it manually adding the URL in prerender.io and is also taking a life and not sure it accomplish the caching.

The website is in development and hosted in heroku http://lataberna.herokuapp.com/#/

**Comment by thoop** [comment]
Sorry we never responded here :( Feel free to email us at support@prerender.io with issues that we can look into.
