### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by brandonparsons** [prerender/prerender_rails#22]
I tried installing this in my Rails 4.2 app, and it doesn't appear to be doing anything.  I've tried on a self-hosted version of Prerender, and your hosted version.  

I'm appending `?_escaped_fragment_=` to my route, but it's just passing right on to the controller instead of handing off to Prerender.

Production.rb:
`config.middleware.use 'Rack::Prerender', protocol: 'https', whitelist: '^/app.*'`

**Comment by brandonparsons** [comment]
I have tried this with and without string-based constant for `Rack::Prerender`

**Comment by thoop** [comment]
Yes, it's working. Can you try it without the whitelist parameter? Maybe that isn't being matched?

Are you running your app in production mode or development mode? Is that config added to the correct file?

Feel free to email me at todd@prerender.io if you want to send me your URL so I can test things.

**Comment by brandonparsons** [comment]
Thank you for the quick reply! I will email you.
