### ISSUE TITLE
Skype support

### ISSUE THREAD

**Issue by rbnunes** [prerender/prerender_rails#23]
Skype now support thumbnails and Title for links. But don't support angular sites.

**Comment by thoop** [comment]
Great idea. Do you know what user agent they are using when crawling URLs linked to in chat?

**Comment by rbnunes** [comment]
I try hard to find the correct user agent. It should include the string skype in it but I couldn't confirm it and found no official source.

**Comment by thoop** [comment]
Added skype user agent check.
