### ISSUE TITLE
Using cache does not set page headers

### ISSUE THREAD

**Issue by wa0x6e** [prerender/prerender_rails#27]
When using redis cache with the after_render/before_render as described in the readme, the raw text response is returned on cached response, and chrome interpret it as a text file instead of parsing the html.

It seems like some headers are missing when returning a cached response

**Comment by thoop** [comment]
That seems weird. I haven't seen that before. Can you email me a URL so I an inspect the result? todd@prerender.io

**Comment by wa0x6e** [comment]
Sorry, our tests server is not public.

This is the headers returned when fetching a not cached results 

```
HTTP/1.1 200 OK
Content-Type: text/html;charset=UTF-8
Content-Length: 32128
Connection: keep-alive
Status: 200 OK
cache-control: max-age=0, private, must-revalidate
date: Fri, 22 Jan 2016 08:32:24 GMT
x-xss-protection: 1; mode=block
server: nginx/1.8.0 + Phusion Passenger 5.0.23
X-Request-Id: 8d3b8dc7-6ed5-46a5-8e98-a3ae696acd90
x-powered-by: Phusion Passenger 5.0.23
etag: W/"b08791d802b1c408c4c40ee26654f602"
x-frame-options: SAMEORIGIN
x-runtime: 0.005809
x-content-type-options: nosniff
Set-Cookie: XSRF-TOKEN=URexTSuYUIr06s7ZeyDZA3NOUm0eWblJbZFUEF3Yc1%2BAD8t3xwg%2B8YIVj8cBZEbLTnTuIaPwRFzFjx%2BhJ%2FC5oQ%3D%3D; path=/_session_id=950a84ec56f66f2d34b5476bf8fb8e12; domain=.kraken.lc; path=/; HttpOnly
Set-Cookie: _session_id=0b3ab1847062578a9b7575ad69f98920; domain=.kraken.lc; path=/; HttpOnly
X-Powered-By: Phusion Passenger 5.0.23
```

When reloading the page, I can confirm via the self installed node prerender console that the page is not sent again to prerender, and the redis-cli monitor console is telling me that a GET request occured. 

The headers of the cached results:

```
HTTP/1.1 200 OK
Content-Length: 32128
Connection: keep-alive
Status: 200 OK
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: f2d2b187-74f5-4acf-88c0-8d64d08efd4e
ETag: W/"84315c79630e41791b28c8171661f6af"
X-Runtime: 0.001753
X-Content-Type-Options: nosniff
Date: Fri, 22 Jan 2016 08:32:46 GMT
Set-Cookie: _session_id=b0e0381ff3e30b1c7698ef034f7c5f22; domain=.kraken.lc; path=/; HttpOnly
X-Powered-By: Phusion Passenger 5.0.23
Server: nginx/1.8.0 + Phusion Passenger 5.0.23
```

The Content-Type header is missing, making:
- Chrome output the code source as text plainly. 
- Safari is downloading the source code as a text file
- The page is rendered correctly on Firefox

**Comment by thoop** [comment]
Can you just add `Content-Type: text/html;charset=UTF-8` to your responses if it's not there already? The Prerender server or caching mechanism doesn't save off headers.

**Comment by wa0x6e** [comment]
I created a PR
