### ISSUE TITLE
Config for adding crawler bot user agents?

### ISSUE THREAD

**Issue by wkoffel** [prerender/prerender_rails#29]
I realized that the `redditbot` which polls for metadata on URLs submitted to Reddit, is not listed in prerender_rails.rb initializer `@crawler_user_agents`.

Now, I could do and fork, customize it, use that, and then issue a pull request for others.  And I see that I can pass the whole list in as an option to the initializer.

It'd be nice if there was an "additional_agents" option which would append (and de-dup) my list with the ones built into the gem.  It's nice to get the automatic updates for new bots when they are added to the distribution, while still being able to extend on my own.

Any thoughts?  Is there another way to accomplish this cleanly?

**Comment by thoop** [comment]
I think that's a good idea. De-dup isn't a huge issue since it's a small list. We could just append `additional_crawler_user_agents ` to the `crawler_user_agents` array.

**Comment by wkoffel** [comment]
So here's a hack I think will work in config.rb until such time as it's an official feature:

```
additional_crawler_agents = ["redditbot"]
config.middleware.use Rack::Prerender, 
    prerender_token: ENV.fetch("PRERENDER_TOKEN"),
    crawler_user_agents: Rack::Prerender.new.instance_variable_get(:@crawler_user_agents).concat(addition_crawler_agents)
```

I need to test and see if it works, but seems reasonable.

**Comment by thoop** [comment]
Haven't had any more interest here and it's easy to add new user agents so we'll close this for now. Feel free to reopen if this is a needed issue for anyone!
