### ISSUE TITLE
Option to ignore query parameters

### ISSUE THREAD

**Issue by jeffmicklos** [prerender/prerender_rails#30]
Prerender is currently holding cache for every query parameter combination of a page, which, for our app is not really necessary. I think it would be a great enhancement to add the option to care about query parameters.

Thoughts?

**Comment by thoop** [comment]
If you are using the Prerender.io hosting service, we can turn that feature on for you from our end. Your middleware would stay the same and we'd just remove all query parameters before doing anything with the URLs. Feel free to email me at todd@prerender.io

If you are not using our hosted service, then you could create a plugin for your Prerender server or implement the `prerender_rails` `before_render` method to strip the query string before trying to do anything in the middleware.

Would that work for you?
