### ISSUE TITLE
Doesn't seem to work for root page

### ISSUE THREAD

**Issue by andrew-teeps** [prerender/prerender_rails#31]
I can successfully get `example.com/users?_escaped_fragment_=` to work, but `example.com/?_escaped_fragment_=` does not.

I have not configured any blacklist or whitelist settings.

I'm using Rails 4.2 and prerender_rails 1.3

**Comment by thoop** [comment]
Do you have the middleware running before all other middleware? Are you serving your index page directly for a request to `/` before the middleware is run? Sounds like something is preventing the Prerender rails middleware from being run when the homepage is accessed.

**Comment by andrewajo** [comment]
I'm having the same issue - as far as I can tell nothing is getting picked up by the middleware at all Rails 4.2.5 and prerender_rails 1.3.0

**Comment by andrew-teeps** [comment]
I moved the middleware to the bottom of the middleware stack and everything worked fine! Which led me to realize that the rails static file middleware was serving index.html from my public folder before my catchall route could route the url to my pages controller.

Thanks for getting back to me, and sorry I didn't respond sooner. :)
