### ISSUE TITLE
301 redirect loop when crawler tries to access website

### ISSUE THREAD

**Issue by habovh** [prerender/prerender_rails#37]
Hi,

We're using the gem since a pretty long time, but we recently switch our web server from Apache to Nginx. I'm not sure what is going on, but accessing the website using a browser or via `curl` works fine.
However, Google bot and other search engines face a 301 redirect infinite loop.

What I've been able to figure out so far:

- Nginx is redirecting once from protocol HTTP (port 80) to HTTPS (port 443).
- Website is publicly accessible through "regular" client
- 301 Redirect loop when client is a bot.
- There's no other handling or special treatment for search engine crawlers than what `prerender_rails` does.

Example with `HTTPie` and `facebookexternalhit` crawler:

This results in a 301 Redirect to the exact same URL
`http GET 'https://www.domain.com/' 'User-Agent':'facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)'`

This works fine
`http GET 'https://www.domain.com/'`

Any idea on why this is happening?

**Comment by habovh** [comment]
Weirdly enough, using `curl` I never get a 301, no matter what `User-Agent` header is set.

This results in `200 OK` using `curl`:
`curl -I "https://t003.allsquaregolf.com" -H "User-Agent: facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"`

As opposed to the `301 Moved Permanently` that `HTTPie` is getting.

**Comment by habovh** [comment]
I can confirm that `prerender_rails` is the culprit triggering the 301 loop.
Removing the middleware results in `200 OK` for every page.
However this is totally bypassing prerender, so that is not a solution, we still need prerender to cache our pages.

**Comment by habovh** [comment]
Forcing protocol to be https resolved the issue for me, but this was really not that easy to debug.

`config.middleware.use Rack::Prerender, protocol: 'https'`

I hope this can help someone someday!

**Comment by thoop** [comment]
Sorry for the inconvenience! Glad you figured that out.

**Comment by dovydaskukalis** [comment]
> [Forcing protocol to be https](https://github.com/prerender/prerender_rails#protocol) resolved the issue for me, but this was really not that easy to debug.
> 
> ```ruby
> config.middleware.use Rack::Prerender, protocol: 'https'
> ```
> 
> I hope this can help someone someday!

And that day has come, thanks! 🎉
